alias h='history'
alias lsa='ls -la'
alias lsl='ls -l'
alias more='less -RX'
alias sl='ls'

alias a='git add'
alias b="git branch"
alias branch="git branch"
alias c='feature commit'
alias checkout="git checkout"
alias co='git checkout'
alias d='clear; git diff -w'
alias l="git log --graph --date=short --pretty=format:'%C(yellow)%h %C(white)%ad %C(black)[%C(green)%an%C(black)] %C(blue)%s%C(yellow)%d'"
alias log='git log -w -u'
alias m='feature merge'
alias master="git checkout master"
alias pop="git stash pop --index"
alias pull="git pull"
alias push="git push"
alias r='feature rebase'
alias s='git status; echo; echo STASH:; git stash list; echo'
alias show='git show -w'
alias stash="git stash save"
alias x='xgrep'


alias sfind='find . -not \( -type d -name .git -prune \) -not \( -type d -name node_modes -prune \) -and \( -type f \)|sort -f'
alias sgrep='find . -not \( -type d -name .git -prune \) -not \( -type d -name node_modes -prune \) -and \( -type f \)|sort -f|xargs grep --color=always'
alias cgrep='grep --color=always'
alias vgrep='grep -v'

function get_feature_commands()
{
  if [ -z $2 ] ; then
    COMPREPLY=(`feature tab`)
  else
    COMPREPLY=(`feature tab $2`)
  fi
}

complete -F get_feature_commands feature

LOCALS=~/.zshrc_locals
if [ -f $LOCALS ]; then
  source $LOCALS
fi
